version: '3.8'

services:

  api-biblioteca1:
    build:
      context: ./api-biblioteca
    expose:
      - "8080"
    networks:
      - app-network

  api-biblioteca2:
    build:
      context: ./api-biblioteca
    expose:
      - "8080"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - cache_data:/var/cache/nginx # Volume para persistir o cache
      - ./.htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt:ro
      - ./nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key:ro
      - ./errors:/usr/share/nginx/html/errors:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api-biblioteca1
      - api-biblioteca2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  cache_data: